### PR TITLE
add SetParameterValues_

### PR DESCRIPTION
**Pull request by waitingkuo**
add the SetParameterValues_ struct

### CODE REVIEW

**Comment by lucacervasio** [comment]
thanks, was this an hint to include the functionality in our cwmp client ?

**Comment by waitingkuo** [comment]
I'm using the library to build a simulator to test HeMS (based on TR-069 ACS) :dancer:

**Comment by lucacervasio** [comment]
Ok cool ! thanks a lot. I don't know HeMS, do you have a link please ?

**Comment by waitingkuo** [comment]
The full name for HeMS is Home eNodeB Management Sysytem. Home eNode B <https://en.wikipedia.org/wiki/Home_eNode_B> provides LTE radio coverage for LTE handset (ex. your iphone :D) And HeMS is to management them.

**Comment by lucacervasio** [comment]
ok thanks for the info, I was curious about the use case as I worked mainly in fiber/dsl broadband access. yes if you want to PR the `client/agent.go` would be great, maybe some stuff can be useful to us as well...

**Comment by waitingkuo** [comment]
I'll make it after refactoring something :) thanks!

**Pull request merged**
